
name: t7cU7vTESk Workflow
description: This is a simple workflow gGftF4R9FZ7S7WmeNODb
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow3.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow3.yml" >> $GITHUB_STEP_SUMMARY
