
name: fS8vzgSHMk Workflow
description: This is a simple workflow 7kigEfOyjEcJq04fm8L5
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow5.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow5.yml" >> $GITHUB_STEP_SUMMARY
