
name: 8iyXQcOA4t Workflow
description: This is a simple workflow NT0cbnoWJBrqRXROW1IR
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow81.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow81.yml" >> $GITHUB_STEP_SUMMARY
