
name: UE4RxIE1rA Workflow
description: This is a simple workflow yfUpuNtxWCigjhlWof3o
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow63.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow63.yml" >> $GITHUB_STEP_SUMMARY
