
name: fTUXXI2Jze Workflow
description: This is a simple workflow 2kjoTdRPB0EwydlZoJkj
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow31.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow31.yml" >> $GITHUB_STEP_SUMMARY
