
name: 0JlUKykD6m Workflow
description: This is a simple workflow QGNEgX9NZORK3V4X1xR1
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow95.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow95.yml" >> $GITHUB_STEP_SUMMARY
