
name: BVTJAi7HGa Workflow
description: This is a simple workflow hUnkTRD0UwIBdBup1yiv
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow50.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow50.yml" >> $GITHUB_STEP_SUMMARY
