
name: NO8TV0f3fF Workflow
description: This is a simple workflow VC5qN3KUqW5LyIdymIJt
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow91.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow91.yml" >> $GITHUB_STEP_SUMMARY
