
name: coc89p5K2P Workflow
description: This is a simple workflow aTTOX4NlikLMxGBCJQsS
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow70.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow70.yml" >> $GITHUB_STEP_SUMMARY
