
name: T0qvpoT7kT Workflow
description: This is a simple workflow HHoMUsJBcaddzvHQt0B2
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow96.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow96.yml" >> $GITHUB_STEP_SUMMARY
