
name: TTuORfpCHA Workflow
description: This is a simple workflow 3M0bcvKHU5VT7mH7N2aQ
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow20.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow20.yml" >> $GITHUB_STEP_SUMMARY
