
name: 4NNBdmfwoX Workflow
description: This is a simple workflow zY8c1bNhnCcm5UARpQ2x
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow84.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow84.yml" >> $GITHUB_STEP_SUMMARY
