
name: AZuC16mLHk Workflow
description: This is a simple workflow 5SvNSjWHyKBEUuY1APx8
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow13.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow13.yml" >> $GITHUB_STEP_SUMMARY
