
name: QSZazWjSS3 Workflow
description: This is a simple workflow 2wNmdRGGcWk3yg1SRfNL
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow78.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow78.yml" >> $GITHUB_STEP_SUMMARY
