
name: cfcpkoHRS3 Workflow
description: This is a simple workflow BCKUurvBMdC1et23f7C2
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow41.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow41.yml" >> $GITHUB_STEP_SUMMARY
