
name: nXm3OiHEJG Workflow
description: This is a simple workflow aLF2o9woyMz9gFEIz3xL
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow27.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow27.yml" >> $GITHUB_STEP_SUMMARY
