
name: XI1zFPZ4QV Workflow
description: This is a simple workflow bZHsj422AbZS2BqSeWU6
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow94.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow94.yml" >> $GITHUB_STEP_SUMMARY
