
name: 6kG2O1e7Ag Workflow
description: This is a simple workflow jcmYAhBIw5RrjgzNbr3c
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow72.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow72.yml" >> $GITHUB_STEP_SUMMARY
