
name: JhT5luYrhA Workflow
description: This is a simple workflow 8prYRVZydehmGYzbtWCZ
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow15.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow15.yml" >> $GITHUB_STEP_SUMMARY
