
name: XiOgFxAg01 Workflow
description: This is a simple workflow Ic84W7yT1nc6CQFtTvf5
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow25.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow25.yml" >> $GITHUB_STEP_SUMMARY
