
name: TZOhlnQBzi Workflow
description: This is a simple workflow IHiJXfFkZ6fD44lBP4Bd
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow3.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow3.yml" >> $GITHUB_STEP_SUMMARY
