
name: hldK5OgkBn Workflow
description: This is a simple workflow GosKlIaEnGKhoZUdcPYK
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow28.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow28.yml" >> $GITHUB_STEP_SUMMARY
