
name: PBqRcG17LR Workflow
description: This is a simple workflow znn5eBJDSkmMiu8vQbr3
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow6.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow6.yml" >> $GITHUB_STEP_SUMMARY
