
name: X9QQsAHWjY Workflow
description: This is a simple workflow mRJNrw4Gp4sQ733hCxUv
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow97.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow97.yml" >> $GITHUB_STEP_SUMMARY
