
name: 7UDA1zYSWk Workflow
description: This is a simple workflow QNkqQAKaa6h2bUWLgrYI
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow26.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow26.yml" >> $GITHUB_STEP_SUMMARY
