
name: oyFgqQM0uj Workflow
description: This is a simple workflow UOzaEma1ohQYNDu0QO3l
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow64.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow64.yml" >> $GITHUB_STEP_SUMMARY
