
name: CxMvWsLG8O Workflow
description: This is a simple workflow R5l5R15SVFIkgUSXuTII
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow93.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow93.yml" >> $GITHUB_STEP_SUMMARY
