
name: SL5rD62OzA Workflow
description: This is a simple workflow tDfOtQViFZwXNcHEPXPS
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow18.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow18.yml" >> $GITHUB_STEP_SUMMARY
