
name: FQMND901FB Workflow
description: This is a simple workflow mHBl9XHVXLhhTv7x1XkD
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow98.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow98.yml" >> $GITHUB_STEP_SUMMARY
