
name: AISAui36Zg Workflow
description: This is a simple workflow CML35HtABEnQbdjKXRPy
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow11.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow11.yml" >> $GITHUB_STEP_SUMMARY
