
name: ePJ6Y4pxKk Workflow
description: This is a simple workflow xw8rQH7EHrHGwUdQKNQt
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow75.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow75.yml" >> $GITHUB_STEP_SUMMARY
