
name: LCQp9OO56z Workflow
description: This is a simple workflow xNhtfX2QgWPWFtbm8kyO
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow7.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow7.yml" >> $GITHUB_STEP_SUMMARY
