
name: rtqXRzDGxr Workflow
description: This is a simple workflow MJDXR6Xrms6e3QYXxzqg
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow33.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow33.yml" >> $GITHUB_STEP_SUMMARY
