name: Hello World Workflow

on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow32.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:

    - name: Say Hello
      run: echo "From workflow32.yml" >> $GITHUB_STEP_SUMMARY
