
name: zrbVEkgGFi Workflow
description: This is a simple workflow YIhOZeh0vzMIZgl3e1zw
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow21.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow21.yml" >> $GITHUB_STEP_SUMMARY
