name: Hello World Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:

    - name: Say Hello
      run: echo "From workflow85.yml" >> $GITHUB_STEP_SUMMARY
