
name: kxMhPamS3g Workflow
description: This is a simple workflow 2f2wYD6pPl7hu0YjOTXW
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow91.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow91.yml" >> $GITHUB_STEP_SUMMARY
