
name: ZS1rRH4FcP Workflow
description: This is a simple workflow pAmmjXYWUoN1SLmg1wKk
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow65.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow65.yml" >> $GITHUB_STEP_SUMMARY
