
name: n7tVvu59zS Workflow
description: This is a simple workflow wT4rSj6hixLY3GJCRUUb
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow60.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow60.yml" >> $GITHUB_STEP_SUMMARY
