
name: Fw9ueSyUwm Workflow
description: This is a simple workflow M3s9PQ1M6hAwcMVwq05B
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow96.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow96.yml" >> $GITHUB_STEP_SUMMARY
