
name: PYuji9xzcU Workflow
description: This is a simple workflow SCoRwH3BMMaI6hrAZ39o
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow100.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow100.yml" >> $GITHUB_STEP_SUMMARY
