
name: UKkOovhmtN Workflow
description: This is a simple workflow 3DQCwxeSOrG8xpH9Q9Oo
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow80.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow80.yml" >> $GITHUB_STEP_SUMMARY
