
name: WMm7N3x2XH Workflow
description: This is a simple workflow 4SlHcjBXyxgfdMDg2rFm
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow20.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow20.yml" >> $GITHUB_STEP_SUMMARY
