
name: n93OWFcyEY Workflow
description: This is a simple workflow n6ndUe4dp83kcf8srE7u
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow12.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow12.yml" >> $GITHUB_STEP_SUMMARY
