
name: zn1TCdOOrZ Workflow
description: This is a simple workflow Zed8iYrA0CtCOvv18eA7
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow17.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow17.yml" >> $GITHUB_STEP_SUMMARY
