
name: Zea9GVtFXh Workflow
description: This is a simple workflow DuLgfuBWyRaoju4f6hph
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow89.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow89.yml" >> $GITHUB_STEP_SUMMARY
