
name: ejEPRhw7Is Workflow
description: This is a simple workflow FRx3HQ3c7OM1fFeeqvKi
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow23.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow23.yml" >> $GITHUB_STEP_SUMMARY
