
name: yoZ1sR1aFq Workflow
description: This is a simple workflow gCfYiZX1Gi2OxFMDMi79
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow95.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow95.yml" >> $GITHUB_STEP_SUMMARY
