
name: lymzOtBDk6 Workflow
description: This is a simple workflow fjDKgEls9lfOcL37fzPh
on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/workflow8.yml
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "From workflow8.yml" >> $GITHUB_STEP_SUMMARY
